### ISSUE TITLE
bug statistics

### ISSUE THREAD

**Issue by louannecostes** [Pixilib/GaelO#469]
statsModel.getReviewStatusData is not a function
    at __WEBPACK_DEFAULT_EXPORT__ (ReviewStatusAndConclusion.js:19:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at HTMLUnknownElement.sentryWrapped (helpers.ts:95:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at performWorkUntilDeadline (scheduler.development.js:533:1)
    at bundle.js:1734:2323
    at h (bundle.js:1734:2438)
    at s (bundle.js:1734:1796)

**Comment by salimkanoun** [comment]
passé dans front
